# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.top = QtWidgets.QWidget(self.centralwidget)
        self.top.setGeometry(QtCore.QRect(50, 30, 979, 89))
        self.top.setAutoFillBackground(False)
        self.top.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Batsmen = QtWidgets.QLabel(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Batsmen.setFont(font)
        self.Batsmen.setObjectName("Batsmen")
        self.horizontalLayout_2.addWidget(self.Batsmen)
        self.Batsmen_value = QtWidgets.QLineEdit(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Batsmen_value.setFont(font)
        self.Batsmen_value.setObjectName("Batsmen_value")
        self.horizontalLayout_2.addWidget(self.Batsmen_value)
        self.Bowler = QtWidgets.QLabel(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bowler.setFont(font)
        self.Bowler.setObjectName("Bowler")
        self.horizontalLayout_2.addWidget(self.Bowler)
        self.Bowler_value = QtWidgets.QLineEdit(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bowler_value.setFont(font)
        self.Bowler_value.setObjectName("Bowler_value")
        self.horizontalLayout_2.addWidget(self.Bowler_value)
        self.All_Rounder = QtWidgets.QLabel(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.All_Rounder.setFont(font)
        self.All_Rounder.setObjectName("All_Rounder")
        self.horizontalLayout_2.addWidget(self.All_Rounder)
        self.All_Rounder_value = QtWidgets.QLineEdit(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.All_Rounder_value.setFont(font)
        self.All_Rounder_value.setObjectName("All_Rounder_value")
        self.horizontalLayout_2.addWidget(self.All_Rounder_value)
        self.Wicket_Keeper = QtWidgets.QLabel(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Wicket_Keeper.setFont(font)
        self.Wicket_Keeper.setObjectName("Wicket_Keeper")
        self.horizontalLayout_2.addWidget(self.Wicket_Keeper)
        self.Wicket_Keeper_value = QtWidgets.QLineEdit(self.top)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Wicket_Keeper_value.setFont(font)
        self.Wicket_Keeper_value.setObjectName("Wicket_Keeper_value")
        self.horizontalLayout_2.addWidget(self.Wicket_Keeper_value)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 120, 981, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.bottom_2 = QtWidgets.QWidget(self.centralwidget)
        self.bottom_2.setGeometry(QtCore.QRect(49, 149, 981, 581))
        self.bottom_2.setAutoFillBackground(True)
        self.bottom_2.setStyleSheet("")
        self.bottom_2.setObjectName("bottom_2")
        self.bottom = QtWidgets.QHBoxLayout(self.bottom_2)
        self.bottom.setContentsMargins(0, 0, 0, 0)
        self.bottom.setObjectName("bottom")
        self.left = QtWidgets.QWidget(self.bottom_2)
        self.left.setAutoFillBackground(False)
        self.left.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left.setObjectName("left")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.left)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.Points_Left = QtWidgets.QLabel(self.left)
        self.Points_Left.setObjectName("Points_Left")
        self.horizontalLayout_5.addWidget(self.Points_Left)
        self.Points_Left_value = QtWidgets.QLineEdit(self.left)
        self.Points_Left_value.setObjectName("Points_Left_value")
        self.horizontalLayout_5.addWidget(self.Points_Left_value)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem5)
        self.Plyer_Category = QtWidgets.QLabel(self.left)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Plyer_Category.setFont(font)
        self.Plyer_Category.setAlignment(QtCore.Qt.AlignCenter)
        self.Plyer_Category.setObjectName("Plyer_Category")
        self.verticalLayout_7.addWidget(self.Plyer_Category)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.BAT_radio = QtWidgets.QRadioButton(self.left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BAT_radio.setFont(font)
        self.BAT_radio.setObjectName("BAT_radio")
        self.horizontalLayout_4.addWidget(self.BAT_radio)
        self.BWL_radio = QtWidgets.QRadioButton(self.left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BWL_radio.setFont(font)
        self.BWL_radio.setObjectName("BWL_radio")
        self.horizontalLayout_4.addWidget(self.BWL_radio)
        self.AR_radio = QtWidgets.QRadioButton(self.left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AR_radio.setFont(font)
        self.AR_radio.setObjectName("AR_radio")
        self.horizontalLayout_4.addWidget(self.AR_radio)
        self.WK_radio = QtWidgets.QRadioButton(self.left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WK_radio.setFont(font)
        self.WK_radio.setObjectName("WK_radio")
        self.horizontalLayout_4.addWidget(self.WK_radio)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.Player_Catergory_value = QtWidgets.QTextEdit(self.left)
        self.Player_Catergory_value.setObjectName("Player_Catergory_value")
        self.verticalLayout_7.addWidget(self.Player_Catergory_value)
        self.bottom.addWidget(self.left)
        spacerItem9 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom.addItem(spacerItem9)
        self.right_2 = QtWidgets.QWidget(self.bottom_2)
        self.right_2.setAutoFillBackground(False)
        self.right_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_2.setObjectName("right_2")
        self.right = QtWidgets.QVBoxLayout(self.right_2)
        self.right.setObjectName("right")
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.right.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.Points_Used = QtWidgets.QLabel(self.right_2)
        self.Points_Used.setObjectName("Points_Used")
        self.horizontalLayout_6.addWidget(self.Points_Used)
        self.Points_Used_value = QtWidgets.QLineEdit(self.right_2)
        self.Points_Used_value.setObjectName("Points_Used_value")
        self.horizontalLayout_6.addWidget(self.Points_Used_value)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.right.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.right.addItem(spacerItem13)
        self.Player_Selected = QtWidgets.QLabel(self.right_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Player_Selected.setFont(font)
        self.Player_Selected.setAlignment(QtCore.Qt.AlignCenter)
        self.Player_Selected.setObjectName("Player_Selected")
        self.right.addWidget(self.Player_Selected)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.right.addItem(spacerItem14)
        self.Team_Name = QtWidgets.QLabel(self.right_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Team_Name.setFont(font)
        self.Team_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Team_Name.setObjectName("Team_Name")
        self.right.addWidget(self.Team_Name)
        self.Player_Selected_value = QtWidgets.QTextEdit(self.right_2)
        self.Player_Selected_value.setObjectName("Player_Selected_value")
        self.right.addWidget(self.Player_Selected_value)
        self.bottom.addWidget(self.right_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 29))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionSave_Team = QtWidgets.QAction(MainWindow)
        self.actionSave_Team.setObjectName("actionSave_Team")
        self.actionEvaluate_Score = QtWidgets.QAction(MainWindow)
        self.actionEvaluate_Score.setObjectName("actionEvaluate_Score")
        self.menuManage_Teams.addAction(self.actionNEW_Team)
        self.menuManage_Teams.addAction(self.actionOPEN_Team)
        self.menuManage_Teams.addAction(self.actionSave_Team)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.actionEvaluate_Score)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Batsmen.setText(_translate("MainWindow", "Batsmen"))
        self.Bowler.setText(_translate("MainWindow", "Bowler"))
        self.All_Rounder.setText(_translate("MainWindow", "All-Rounder"))
        self.Wicket_Keeper.setText(_translate("MainWindow", "Wicket-Keeper"))
        self.Points_Left.setText(_translate("MainWindow", "Points Left:"))
        self.Plyer_Category.setText(_translate("MainWindow", "Player Category"))
        self.BAT_radio.setText(_translate("MainWindow", "BAT"))
        self.BWL_radio.setText(_translate("MainWindow", "BWL"))
        self.AR_radio.setText(_translate("MainWindow", "AR"))
        self.WK_radio.setText(_translate("MainWindow", "WK"))
        self.Points_Used.setText(_translate("MainWindow", "Points Used:"))
        self.Player_Selected.setText(_translate("MainWindow", "Player Selected"))
        self.Team_Name.setText(_translate("MainWindow", "Team_Name"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "New Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "Open Team"))
        self.actionSave_Team.setText(_translate("MainWindow", "Save Team"))
        self.actionEvaluate_Score.setText(_translate("MainWindow", "Evaluate Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
